language: haskell

script:
  - cabal install --only-dependencies && cabal configure && cabal build

ghc:
  - 7.10
  - 8.0

notifications:
  email:
      - alpmestan@gmail.com
  irc: "irc.freenode.org#haskell-math"
